adel /a /f /s /q "%userprofile%\AppData\Local\Microsoft\Windows\Temporary Internet Files" 
del /a /f /s /q "%userprofile%\AppData\Roaming\Microsoft\Windows\Cookies" 
del /a /f /s /q "%SYSTEMDRIVE%\SoftwareDistribution\Download\SharedFileCache"
del /a /f /s /q "%SYSTEMDRIVE%\Temp"
del /a /f /s /q "%WINDIR%\Temp"
del /a /f /s /q "%WINDIR%\Prefetch"
del /a /f /s /q "%TEMP%"
del /a /f /s /q "%Tmp%"
del /a /f /s /q "%SystemRoot%\TEMP"
del /a /f /s /q "%userprofile%\AppData\Local\Temp"
del /a /f /s /q "%userprofile%\AppData\Local\Google\Chrome\User Data\Default\cache"
del /a /f /s /q "%userprofile%\AppData\Local\Google\Chrome\User Data\Default\Media Cache"
del /a /f /s /q "%userprofile%\AppData\Local\Yandex\YandexBrowser\User Data\Default\Media Cache"
del /a /f /s /q "%userprofile%\AppData\Local\Opera Software\Opera Stable\Media Cache"
del /a /f /s /q "%userprofile%\AppData\Local\Opera Software\Opera Stable\Cache"
del /a /f /s /q "%userprofile%\AppData\Local\Yandex\YandexBrowser\User Data\Default\Cache"
del /a /f /s /q "%userprofile%\AppData\Local\Microsoft\Internet Explorer\CacheStorage"
del /a /f /s /q "%userprofile%\AppData\Local\Mozilla\Firefox\Profiles\ah8zpabp.default\OfflineCache"
del /a /f /s /q "%userprofile%\AppData\Local\Mozilla\Firefox\Profiles\ah8zpabp.default\startupCache"
del /a /f /s /q "%userprofile%\AppData\Roaming\Microsoft\Windows\Recent"
del /a /f /s /q "%WINDIR%\SoftwareDistribution\Download"
del /a /f /s /q "%WINDIR%\Installer"
rd /s /q "%systemdrive%\$Recycle.bin"
